### ISSUE TITLE
"Indie" genre mapping

### ISSUE THREAD

**Issue by johnliu55tw** [LinYunWen/smart-player#1]
I think the labels that map to "Indie" genre (in all categories) should be `["獨立", "硬地"]`, instead of `["清新", "自然", "乾淨"]`. For instance, in the `Category.kt`, there is such a mapping:
```
"Soft Indie Pop" to arrayOf("清新", "自然", "乾淨")
```
And this should be:
```
"Soft Indie Pop" to arrayOf("獨立", "硬地")
```

**Comment by LinYunWen** [comment]
You are right. I adjust the key word for Soft indie in commit [318d12a](https://github.com/LinYunWen/smart-player/commit/318d12a36828c83ccb6310773d6214ebc9ab60c7).
Thank you for reminding.
